### ISSUE TITLE
All icons are crowns

### ISSUE THREAD

**Issue by ricardovanlaarhoven** [kingscode/vue-cli-plugin-kingscode-scaffold#33]
All icons inside src/plugins/vuetify/FontawesomeFree.js are font awesome crown icons

**Comment by jvhellemondt** [comment]
I remember it being intentional. I do not remember why tho

**Comment by ricardovanlaarhoven** [comment]
Also the vuetify resource icons do not work anymore with the scaffolds new svg icons

**Comment by jvhellemondt** [comment]
Closed by https://github.com/kingscode/vue-cli-plugin-kingscode-scaffold/pull/35
